// <auto-generated />
using System;
using InfiniteContentAI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfiniteContentAI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818174601_AddPipelineExecutionsAndArtifacts")]
    partial class AddPipelineExecutionsAndArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InfiniteContentAI.Domain.Artifacts.Artifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_execution_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("StepExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_execution_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_artifacts_project_id");

                    b.HasIndex("StepExecutionId")
                        .IsUnique()
                        .HasDatabaseName("ux_artifacts_step_execution_id");

                    b.HasIndex("PipelineExecutionId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_artifacts_execution_created_at_id");

                    b.ToTable("artifacts", null, t =>
                        {
                            t.HasCheckConstraint("ck_artifacts_content_length", "char_length(content) BETWEEN 1 AND 100000");

                            t.HasCheckConstraint("ck_artifacts_type_valid", "type IN ('Research', 'Script')");
                        });
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Executions.PipelineExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_message");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.Property<int>("PipelineVersion")
                        .HasColumnType("integer")
                        .HasColumnName("pipeline_version");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId")
                        .HasDatabaseName("ix_pipeline_executions_pipeline_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_pipeline_executions_project_id");

                    b.HasIndex("OrganizationId", "PipelineId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_pipeline_executions_organization_pipeline_created_at_id");

                    b.HasIndex("OrganizationId", "ProjectId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_pipeline_executions_organization_project_created_at_id");

                    b.ToTable("pipeline_executions", null, t =>
                        {
                            t.HasCheckConstraint("ck_pipeline_executions_pipeline_version_positive", "pipeline_version > 0");

                            t.HasCheckConstraint("ck_pipeline_executions_status_valid", "status IN ('Pending', 'Running', 'Completed', 'Failed')");
                        });
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Executions.StepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_message");

                    b.Property<Guid>("PipelineExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_execution_id");

                    b.Property<Guid>("PipelineStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_step_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PipelineStepId")
                        .HasDatabaseName("ix_step_executions_pipeline_step_id");

                    b.HasIndex("PipelineExecutionId", "PipelineStepId")
                        .IsUnique()
                        .HasDatabaseName("ux_step_executions_execution_pipeline_step");

                    b.HasIndex("PipelineExecutionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_step_executions_execution_position");

                    b.ToTable("step_executions", null, t =>
                        {
                            t.HasCheckConstraint("ck_step_executions_position_positive", "position > 0");

                            t.HasCheckConstraint("ck_step_executions_status_valid", "status IN ('Pending', 'Running', 'Completed', 'Failed')");

                            t.HasCheckConstraint("ck_step_executions_type_valid", "type IN ('Research', 'Script')");
                        });
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Pipelines.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_pipelines_project_id");

                    b.HasIndex("OrganizationId", "ProjectId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_pipelines_organization_project_created_at_id");

                    b.ToTable("pipelines", (string)null);
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Pipelines.PipelineStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uuid")
                        .HasColumnName("pipeline_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_pipeline_steps_pipeline_position");

                    b.HasIndex("PipelineId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ux_pipeline_steps_pipeline_type");

                    b.ToTable("pipeline_steps", null, t =>
                        {
                            t.HasCheckConstraint("ck_pipeline_steps_position_positive", "position > 0");
                        });
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_projects_organization_created_at_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Artifacts.Artifact", b =>
                {
                    b.HasOne("InfiniteContentAI.Domain.Executions.PipelineExecution", null)
                        .WithMany()
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfiniteContentAI.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfiniteContentAI.Domain.Executions.StepExecution", null)
                        .WithMany()
                        .HasForeignKey("StepExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Executions.PipelineExecution", b =>
                {
                    b.HasOne("InfiniteContentAI.Domain.Pipelines.Pipeline", null)
                        .WithMany()
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InfiniteContentAI.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Executions.StepExecution", b =>
                {
                    b.HasOne("InfiniteContentAI.Domain.Executions.PipelineExecution", null)
                        .WithMany("Steps")
                        .HasForeignKey("PipelineExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfiniteContentAI.Domain.Pipelines.PipelineStep", null)
                        .WithMany()
                        .HasForeignKey("PipelineStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Pipelines.Pipeline", b =>
                {
                    b.HasOne("InfiniteContentAI.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Pipelines.PipelineStep", b =>
                {
                    b.HasOne("InfiniteContentAI.Domain.Pipelines.Pipeline", null)
                        .WithMany("Steps")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Executions.PipelineExecution", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("InfiniteContentAI.Domain.Pipelines.Pipeline", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
