<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\InfiniteContentAI.Application\InfiniteContentAI.Application.csproj" />
    <ProjectReference Include="..\InfiniteContentAI.Domain\InfiniteContentAI.Domain.csproj" />
    <ProjectReference Include="..\InfiniteContentAI.Contracts\InfiniteContentAI.Contracts.csproj" />
    <ProjectReference Include="..\InfiniteContentAI.SharedKernel\InfiniteContentAI.SharedKernel.csproj" />
  </ItemGroup>
</Project>
